<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>../../target/dotnet/recovery-obj/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>../../target/dotnet/recovery-obj/</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>BgiBridge.Recovery</AssemblyName>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>../../target/dotnet/recovery/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RecoveryProgram.cs" />
    <ProjectReference Include="../managed/BgiBridge.csproj" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
