<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>../.build/contracts-obj/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>../.build/contracts-obj/</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>../.build/contracts/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ContractTests.cs" />
    <ProjectReference Include="../managed/BgiBridge.csproj" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
